# Generated by Django 4.0.5 on 2022-07-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tic', models.CharField(max_length=5, verbose_name='Название')),
                ('leverage', models.IntegerField(verbose_name='Умножение')),
                ('entry_price', models.FloatField(verbose_name='Цена входа')),
                ('position_amt', models.FloatField(verbose_name='Кол-во')),
                ('liquidation_price', models.FloatField(verbose_name='Цена ликвидации')),
                ('mark_price', models.FloatField(verbose_name='Цена')),
                ('unrealized_profit', models.FloatField(verbose_name='Плюс')),
                ('notional', models.FloatField(verbose_name='Оъем')),
                ('warning', models.FloatField(verbose_name='Ликвидация')),
            ],
        ),
    ]
